"""Add budgeting data models and fields

Revision ID: 38e48b38d4dd
Revises: 336f32678810
Create Date: 2025-06-18 16:48:11.730331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e48b38d4dd'
down_revision: Union[str, None] = '336f32678810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('budget_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_year_month_budget')
    )
    op.create_index(op.f('ix_monthly_budgets_id'), 'monthly_budgets', ['id'], unique=False)
    op.add_column('accounts', sa.Column('purpose', sa.Enum('PERSONAL', 'BUSINESS', name='accountpurpose'), server_default='PERSONAL', nullable=False))
    op.add_column('subcategories', sa.Column('is_reimbursable', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('subcategories', sa.Column('exclude_from_budget', sa.Boolean(), server_default='0', nullable=False))

    
    op.add_column('transactions', sa.Column('linked_transaction_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transactions_linked_transaction_hash'), 'transactions', ['linked_transaction_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_linked_transaction_hash'), table_name='transactions')
    op.drop_column('transactions', 'linked_transaction_hash')
    op.drop_column('subcategories', 'exclude_from_budget')
    op.drop_column('subcategories', 'is_reimbursable')
    op.drop_column('accounts', 'purpose')
    op.drop_index(op.f('ix_monthly_budgets_id'), table_name='monthly_budgets')
    op.drop_table('monthly_budgets')
    # ### end Alembic commands ###