"""Add override_reimbursable to transactions

Revision ID: 50622b6b5874
Revises: 38e48b38d4dd
Create Date: 2025-06-19 15:29:17.798836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50622b6b5874'
down_revision: Union[str, None] = '38e48b38d4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('override_reimbursable', sa.Boolean(), nullable=True))
    op.drop_index(op.f('ix_transactions_subcategory_id'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_subcategory_id'), 'transactions', ['subcategory_id'], unique=False)
    op.drop_column('transactions', 'override_reimbursable')
    # ### end Alembic commands ###
