"""create_accounts_table_and_restructure_transactions_fk

Revision ID: ccb1a5dfa2ae
Revises: 075b0ea2a3e8
Create Date: 2025-06-10 11:17:43.981908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccb1a5dfa2ae'
down_revision: Union[str, None] = '075b0ea2a3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('account_type', sa.Enum('SAVINGS_ACCOUNT', 'CREDIT_CARD', 'WALLET', 'UNKNOWN', name='accounttype'), nullable=False),
        sa.Column('bank_name', sa.String(length=100), nullable=False),
        sa.Column('account_last4', sa.String(length=4), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bank_name', 'account_last4', name='uq_bank_account_last4')
    )
    op.create_index(op.f('ix_accounts_bank_name'), 'accounts', ['bank_name'], unique=False)
    op.create_index(op.f('ix_accounts_account_last4'), 'accounts', ['account_last4'], unique=False)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index('ix_bank_account_last4_composite', 'accounts', ['bank_name', 'account_last4'], unique=False)
    
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_transactions_account_id_accounts",
            'accounts', 
            ['account_id'],
            ['id']
        )
        # Drop the old columns
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('account_identifier')
    
    # ### end Alembic commands ###
    
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('transactions', sa.Column('account_identifier', sa.VARCHAR(length=100), nullable=True))
    op.add_column('transactions', sa.Column('bank_name', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.alter_column('transactions', 'merchant_vpa',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('transactions', 'account_id')
    # ### end Alembic commands ###
