"""add_telegram_message_id_to_transactions

Revision ID: e71bd987c3bf
Revises: 145aec49a5e5
Create Date: 2025-06-12 10:57:24.466288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71bd987c3bf'
down_revision: Union[str, None] = '145aec49a5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_telegram_message_id'), 'transactions', ['telegram_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_telegram_message_id'), table_name='transactions')
    op.drop_column('transactions', 'telegram_message_id')
    # ### end Alembic commands ###
